[workspace]
resolver = "2"
members = [
    "security-framework-sys",
    "security-framework",
    "iostest",
    "systest"
]

[patch.crates-io]
security-framework-sys.path = "security-framework-sys"
security-framework.path = "security-framework"
