name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - { name: msrv, version: 1.60.0 }
          - { name: stable, version: stable }
          - { name: beta, version: beta }

    runs-on: macos-latest

    name: Test (${{ matrix.rust.name }})

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust (${{ matrix.rust.name }})
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: ${{ matrix.rust.version }}

      - name: MSRV workarounds
        if: ${{ matrix.rust.name == 'msrv' }}
        run: |
          cargo generate-lockfile
          cargo update -p=time --precise=0.3.17
          cargo update -p=is-terminal --precise=0.4.7
          cargo update -p=dashmap --precise=5.4.0
          cargo update -p=tempfile --precise=3.6.0

      - name: Run cargo test
        run: cargo test --workspace --all-features

      - name: Check default features
        run: cargo check --workspace

  ios:
    name: Check iOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          target: aarch64-apple-ios

      - name: Run check
        run: cargo check -p=security-framework --target=aarch64-apple-ios --all-features

  apple-silicon:
    name: Check Apple Silicon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          target: aarch64-apple-darwin

      - name: Run check
        run: cargo check -p=security-framework --target=aarch64-apple-darwin --all-features
