name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        rust:
          - 1.60.0 # MSRV
          - stable
          - beta

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: ${{ matrix.rust }}

        # `x509_parser` dev-dependency has transitive dependency `time` which
        # has a 6-month MSRV policy, don't run tests on MSRV version since they
        # will always fail.
      - name: Revert time dep if needed
        if: ${{ matrix.rust == '1.60.0' }}
        run: cargo update -p=time --precise=0.3.17

      - name: Run cargo test
        run: cargo test --workspace --all-features

      - name: Check default features
        run: cargo check --workspace

  ios:
    name: iOS compile-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: stable
          target: aarch64-apple-ios

      - name: Run check
        run: cargo check -p=security-framework --target=aarch64-apple-ios --all-features

  apple-silicon:
    name: Apple Silicon compile-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
      - name: Run check
        run: cargo check -p=security-framework --target=aarch64-apple-darwin --all-features
